"""User Table added

Revision ID: d28afa99c327
Revises: db96039d2c39
Create Date: 2026-07-01 14:54:32.341683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28afa99c327'
down_revision: Union[str, Sequence[str], None] = 'db96039d2c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=225), nullable=False),
        sa.Column("email", sa.String(length=225), nullable=False),
        sa.Column("hashed_password", sa.String(length=225), nullable=False),
        sa.Column("role", sa.String(length=225), nullable=False, server_default=sa.text("'Candidate'")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
